module.exports.config = {
    "name": "fact",
    "version": "1.0.0",
    "role": 0,
    "author": "Hùng",
    "info": "fun fact",
    "Category": "Tiện ích",
    "cd": 0
};

module.exports.onRun = function({ api, event }) {
    // Danh sách 100 sự thật thú vị
    const facts = [
        "Bạn có biết? Mật ong không bao giờ hỏng. Các nhà khảo cổ học đã tìm thấy những hũ mật ong trong các ngôi mộ Ai Cập cổ đại có tuổi đời hơn 3.000 năm và vẫn ăn được.",
        "Khoảng thời gian lâu nhất giữa hai lần sinh đôi là 87 ngày.",
        "Sò điệp có ba trái tim và máu màu xanh.",
        "Một nhóm chim hồng hạc gọi là 'flamboyance'.",
        "Chuối là quả mọng, nhưng dâu tây thì không.",
        "Tháp Eiffel có thể cao hơn 15 cm vào mùa hè do sự mở rộng nhiệt.",
        "Một con bạch tuộc có chín bộ não.",
        "Một ngày trên sao Kim dài hơn một năm trên sao Kim.",
        "Phân của wombat có hình dạng khối lập phương.",
        "Có một loại ong không bao giờ chết trong mùa đông.",
        "Những con ruồi có thể nhảy lên đến 15 cm mỗi lần nhảy.",
        "Gấu bắc cực có thể bơi xa hơn 320 km để tìm kiếm thức ăn.",
        "Tôm hùm có thể sống đến hơn 50 năm trong môi trường tự nhiên.",
        "Con người và chuột có đến 90% DNA giống nhau.",
        "Cá heo có thể ngủ với một nửa não của chúng, phần còn lại vẫn hoạt động để giữ an toàn.",
        "Mỗi năm, trái đất hấp thụ khoảng 40 triệu tấn bụi từ không gian.",
        "Con người có khoảng 206 xương trong cơ thể, nhưng trẻ sơ sinh có khoảng 270 xương.",
        "Dê có thể phân biệt giữa các biểu cảm khuôn mặt của con người.",
        "Một con sứa có thể sống đến hàng nghìn năm.",
        "Có hơn 1.000 loài động vật có thể sống trên chỉ một cây.",
        "Cá mập không có xương, chúng có sụn.",
        "Ngựa có thể ngủ đứng và khi nằm xuống thì thường chỉ ngủ trong thời gian ngắn.",
        "Con người có khoảng 5 triệu lỗ chân lông trên cơ thể.",
        "Có những con gà mái có thể đẻ trứng không có vỏ.",
        "Sư tử có thể ngủ đến 20 giờ mỗi ngày.",
        "Trái đất quay quanh trục của nó với tốc độ khoảng 1.670 km/h.",
        "Tổng số của các ngón tay và ngón chân trên cơ thể con người là 20.",
        "Đại dương chiếm khoảng 71% bề mặt của trái đất.",
        "Từ khi bắt đầu đến hiện tại, loài người đã phát minh ra hơn 1.000 loại phấn trang điểm.",
        "Chó có thể nghe âm thanh ở tần số cao hơn gấp ba lần so với con người.",
        "Tất cả các loài chim đều có lông.",
        "Những con bướm có thể nhận biết mùi vị bằng chân của chúng.",
        "Một giọt nước trong đại dương có thể chứa hàng triệu vi sinh vật.",
        "Chúng ta có thể mất đến 50% lượng nước cơ thể trong một số tình huống khẩn cấp mà vẫn sống sót.",
        "Cá hồi có thể sống đến 7 năm trong tự nhiên.",
        "Đầu của con gấu có thể quay một cách linh hoạt để nhìn về phía sau.",
        "Hươu có thể nhảy cao đến 3 mét.",
        "Một số loài rùa có thể sống đến 150 năm.",
        "Có hơn 2.000 loại cây có thể được sử dụng làm thuốc.",
        "Những con rồng Komodo là loài thằn lằn lớn nhất trên thế giới.",
        "Đại dương chứa khoảng 80% sự sống trên trái đất.",
        "Một số con sên có thể sống đến 10 năm.",
        "Cá mập có thể nhận biết các sóng điện từ của con mồi.",
        "Có hơn 2 triệu loài côn trùng được biết đến.",
        "Cá mú có thể sống đến hơn 100 năm.",
        "Có khoảng 500 triệu con ruồi trên trái đất.",
        "Tỷ lệ phần trăm của oxy trong không khí là khoảng 21%.",
        "Mỗi phút có khoảng 50.000 tế bào da bị mất đi từ cơ thể con người.",
        "Cá ngựa có thể bơi ngược.",
        "Chó có thể cảm nhận được cảm xúc của con người qua mùi hương.",
        "Con người có thể tạo ra khoảng 1 lít nước miếng mỗi ngày.",
        "Mỗi loại vỏ sò có một hình dạng và màu sắc riêng biệt.",
        "Cá voi xanh là động vật lớn nhất trên trái đất.",
        "Cú có thể quay đầu 270 độ.",
        "Gà có thể nhìn thấy trong ánh sáng hồng ngoại.",
        "Có khoảng 400 triệu năm kể từ khi loài cá đầu tiên xuất hiện trên trái đất.",
        "Những con tôm hùm có thể thay đổi màu sắc của chúng để thích nghi với môi trường.",
        "Có một loại cá có thể sống trên cạn và bơi lội dưới nước.",
        "Mỗi con người có một kiểu vân tay riêng biệt.",
        "Số lượng vi khuẩn trong miệng bạn có thể lên đến hàng triệu.",
        "Hầu hết các loài chim có khả năng bay xa hơn 1.000 km không nghỉ.",
        "Có hơn 7.000 ngôn ngữ được nói trên toàn thế giới.",
        "Mỗi năm, trái đất nhận được khoảng 2 triệu tấn bụi từ không gian.",
        "Gấu trúc ăn hơn 10.000 cây tre mỗi ngày.",
        "Những con chuột có thể sống mà không có đầu trong một thời gian ngắn.",
        "Một số loài cây có thể sống hàng nghìn năm.",
        "Mỗi người có một số lượng độc nhất vô nhị các triệu chứng sinh lý.",
        "Một số con ruồi có thể sống đến 2 tháng mà không cần ăn.",
        "Mắt của con người có thể phân biệt hơn 10 triệu màu sắc khác nhau.",
        "Tất cả các loài vật đều có hệ thống miễn dịch.",
        "Mỗi người có khoảng 2 triệu tuyến mồ hôi trong cơ thể.",
        "Có một loại sứa có thể tự tái tạo hoàn toàn nếu bị cắt thành nhiều mảnh.",
        "Những con cừu có thể nhận ra các biểu cảm khuôn mặt của các con cừu khác.",
        "Một số loài động vật có thể phát sáng trong bóng tối.",
        "Cây dương xỉ là một trong những loài thực vật đầu tiên xuất hiện trên trái đất.",
        "Có khoảng 300 triệu năm kể từ khi loài ếch đầu tiên xuất hiện.",
        "Hầu hết các loài chim có thể cảm nhận được từ trường trái đất.",
        "Một số con rùa có thể thở qua da.",
        "Đôi mắt của con người có thể phân biệt hơn 10 triệu sắc thái màu.",
        "Có hơn 500.000 loại côn trùng trên thế giới.",
        "Một số loài động vật có thể tạo ra âm thanh có tần số cao hơn khả năng nghe của con người.",
        "Tỷ lệ phần trăm của nước trong cơ thể con người là khoảng 60%.",
        "Mỗi người có một mùi cơ thể đặc trưng riêng.",
        "Có hơn 5.000 loài cây có thể được sử dụng để làm thuốc.",
        "Một số loài động vật có thể cảm nhận được sự thay đổi trong thời tiết.",
        "Có khoảng 100 tỷ tế bào thần kinh trong não người.",
        "Các loài chim có thể nhìn thấy ở ánh sáng hồng ngoại.",
        "Con người có thể tạo ra khoảng 20.000 lít nước miếng trong suốt cuộc đời.",
        "Cây dương xỉ có thể sống ở các môi trường khắc nghiệt.",
        "Có hơn 10.000 loài động vật có thể được tìm thấy trong một khu rừng nhiệt đới.",
        "Mỗi người có một kiểu vân tay và dấu chân độc nhất.",
        "Số lượng vi khuẩn trong cơ thể người có thể gấp 10 lần số lượng tế bào.",
        "Mỗi loại hoa có thể có mùi hương riêng biệt.",
        "Có hơn 1 triệu loài côn trùng trên trái đất.",
        "Một số con cá có thể thay đổi màu sắc của chúng để hòa trộn với môi trường.",
        "Những con chim có thể bay xa hơn 10.000 km không nghỉ.",
        "Có khoảng 300 triệu năm kể từ khi loài rùa đầu tiên xuất hiện.",
        "Một số loài động vật có thể sống mà không cần nước trong một thời gian dài.",
        "Cá voi có thể giao tiếp qua những âm thanh có tần số thấp.",
        "Có hơn 2 triệu loài thực vật trên trái đất.",
        "Một số con cá có thể thở trên cạn.",
        "Mỗi ngày có khoảng 1.000 loài mới được phát hiện.",
        "Có hơn 7.000 loài động vật được biết đến.",
        "Một số loài cây có thể sinh sản mà không cần thụ phấn.",
        "Cây gỗ có thể sống hàng ngàn năm.",
        "Có hơn 5.000 loài động vật được biết đến trên thế giới.",
        "Mỗi người có một kiểu dáng lông tóc và màu da riêng biệt.",
        "Có hơn 2 triệu loài thực vật được phát hiện trên trái đất.",
        "Một số loài động vật có thể sống trong các môi trường cực đoan.",
        "Mỗi ngày có khoảng 100 triệu tế bào chết trong cơ thể người.",
        "Có hơn 10.000 loài côn trùng được biết đến.",
        "Một số loài cá có thể sống lâu hơn 50 năm.",
        "Có hơn 1.000 loài thực vật được sử dụng làm thuốc.",
        "Một số loài động vật có thể tự tái tạo các bộ phận cơ thể của chúng.",
        "Có hơn 500 triệu loài vi khuẩn được phát hiện.",
        "Một số loài thực vật có thể sống trong môi trường khô cằn.",
        "Có hơn 200 triệu năm kể từ khi loài cá đầu tiên xuất hiện.",
        "Một số loài động vật có thể phát sáng trong bóng tối để thu hút con mồi.",
        "Có hơn 5.000 loài thực vật được sử dụng trong y học cổ truyền.",
        "Một số loài động vật có thể phát ra âm thanh để giao tiếp với nhau.",
        "Có hơn 1 triệu loài côn trùng được biết đến.",
        "Một số loài động vật có thể nhận biết được cảm xúc của con người.",
        "Có hơn 7.000 loài cây trên thế giới.",
        "Một số loài động vật có thể sống ở các độ cao rất lớn.",
        "Có hơn 2 triệu loài thực vật được phát hiện.",
        "Một số loài động vật có thể thay đổi màu sắc của chúng để bảo vệ mình.",
        "Có hơn 300 triệu năm kể từ khi loài cá đầu tiên xuất hiện.",
        "Một số loài động vật có thể sống mà không có nước trong một thời gian dài.",
        "Có hơn 1.000 loài thực vật được sử dụng trong y học hiện đại.",
        "Một số loài động vật có thể sống trong môi trường cực lạnh.",
        "Có hơn 10.000 loài động vật được biết đến trên thế giới.",
        "Một số loài thực vật có thể sống trong môi trường khô cằn.",
        "Có hơn 500 triệu loài vi khuẩn được phát hiện.",
        "Một số loài động vật có thể tự tái tạo các bộ phận cơ thể của chúng.",
        "Có hơn 7.000 loài thực vật trên thế giới.",
        "Một số loài động vật có thể giao tiếp qua âm thanh.",
        "Có hơn 200 triệu năm kể từ khi loài cá đầu tiên xuất hiện.",
        "Một số loài động vật có thể sống ở các độ cao rất lớn.",
        "Có hơn 5.000 loài thực vật được phát hiện.",
        "Một số loài động vật có thể thay đổi màu sắc của chúng để hòa trộn với môi trường.",
        "Có hơn 1 triệu loài côn trùng được biết đến.",
        "Một số loài thực vật có thể sinh sản mà không cần thụ phấn.",
        "Có hơn 10.000 loài động vật được biết đến.",
        "Một số loài động vật có thể sống trong các môi trường cực kỳ khắc nghiệt.",
        "Có hơn 2 triệu loài thực vật trên trái đất.",
        "Một số loài động vật có thể phát ra âm thanh để thu hút con mồi.",
        "Có hơn 5.000 loài động vật được phát hiện.",
        "Một số loài thực vật có thể sống ở các môi trường khô cằn.",
        "Có hơn 1.000 loài động vật được biết đến.",
        "Một số loài động vật có thể tự tái tạo các bộ phận cơ thể của chúng.",
        "Có hơn 7.000 loài thực vật được phát hiện.",
        "Một số loài động vật có thể sống trong các môi trường cực kỳ khắc nghiệt.",
        "Có hơn 10.000 loài động vật được biết đến.",
        "Một số loài thực vật có thể sinh sản mà không cần thụ phấn.",
        "Có hơn 5.000 loài thực vật được phát hiện.",
        "Một số loài động vật có thể thay đổi màu sắc của chúng để bảo vệ mình.",
        "Có hơn 1 triệu loài côn trùng được phát hiện.",
        "Một số loài động vật có thể giao tiếp qua âm thanh.",
        "Có hơn 2 triệu loài thực vật trên trái đất.",
        "Một số loài động vật có thể phát sáng trong bóng tối để thu hút con mồi.",
        "Có hơn 7.000 loài thực vật được phát hiện.",
        "Một số loài động vật có thể sống trong các môi trường cực kỳ khắc nghiệt.",
        "Có hơn 10.000 loài động vật được biết đến.",
        "Một số loài thực vật có thể sinh sản mà không cần thụ phấn.",
        "Có hơn 1.000 loài động vật được biết đến.",
        "Một số loài động vật có thể tự tái tạo các bộ phận cơ thể của chúng.",
        "Có hơn 5.000 loài thực vật được phát hiện.",
        "Một số loài động vật có thể thay đổi màu sắc của chúng để hòa trộn với môi trường.",
        "Có hơn 7.000 loài thực vật trên thế giới.",
        "Một số loài động vật có thể sống trong các môi trường khô cằn.",
        "Có hơn 10.000 loài động vật được phát hiện.",
        "Một số loài thực vật có thể sinh sản mà không cần thụ phấn.",
        "Có hơn 2 triệu loài thực vật trên trái đất.",
        "Một số loài động vật có thể phát sáng trong bóng tối.",
        "Có hơn 5.000 loài động vật được phát hiện.",
        "Một số loài thực vật có thể thay đổi màu sắc của chúng để hòa trộn với môi trường.",
        "Có hơn 1 triệu loài côn trùng được biết đến.",
        "Một số loài động vật có thể sống trong các môi trường cực kỳ khắc nghiệt.",
        "Có hơn 7.000 loài thực vật được phát hiện.",
        "Một số loài động vật có thể giao tiếp qua âm thanh.",
        "Có hơn 10.000 loài động vật được biết đến."
    ];

    // Chọn một sự thật ngẫu nhiên từ danh sách
    const randomFact = facts[Math.floor(Math.random() * facts.length)];

    // Gửi sự thật thú vị
    return api.sendMessage(randomFact, event.threadID, event.messageID);
};
